### ISSUE TITLE
Callable: Introduction of double splat breaks keyword parameters

### ISSUE THREAD

**Issue by raychatter** [thread-pond/junk_drawer#28]
**What**
The [recent introduction](https://github.com/thread-pond/junk_drawer/pull/26) of the double splat (`**`) operator to `Callable` has caused `call` methods with default parameter values to break.

**Steps to reproduce**
Add the following test to `callable_spec`:
```ruby
it 'works when there is a default parameter' do
  class MyCallableClass
    include JunkDrawer::Callable
    def call(who = 'World')
      "Hello, #{who}!"
    end
  end

  expected = "Hello, World!"
  expect(MyCallableClass.()).to eq expected
end
```
The following error is received:
```ruby
  1) JunkDrawer::Callable works when there is a default parameter
     Failure/Error: expect(MyCallableClass.()).to eq expected
     
       expected: "Hello, World!"
            got: "Hello, {}!"
     
       (compared using ==)
     # ./spec/junk_drawer/callable_spec.rb:20:in `block (2 levels) in <top (required)>'
```

**Comment by mockdeep** [comment]
@raychatter thanks for reporting. I opened a PR [here](https://github.com/thread-pond/junk_drawer/pull/29) that should fix the issue.
